server:
  port: 9001
spring:
  application:
    name: demo-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@peer1:8761/eureka,http://user:123456@peer2:8762/eureka
  instance:
    prefer-ip-address: true
